version: '2'

services:
    base:
        build:
            context: .
            dockerfile: docker/base/Dockerfile
        image: lucida/base
        entrypoint: echo 'base'

    mongodb:
        image: mongo:3.2
        volumes:
            - ./mongodb_data:/data
        expose:
            - "27017"

    commandcenter:
        depends_on:
            - base
        links:
            - mongodb
            - questionanswering
            - imagematching
            - calendar
 #            - speechrecognition
        build:
            context: .
            dockerfile: docker/commandcenter/Dockerfile
        image: lucida/commandcenter
        ports:
            - 3000:3000
            - 8081:8081
        expose:
            - "8081"
        environment:
            - MONGO_PORT_27017_TCP_ADDR=mongodb
            - QA_PORT_8083_TCP_ADDR=questionanswering
            - CA_PORT_8084_TCP_ADDR=calendar
            - IMM_PORT_8082_TCP_ADDR=imagematching
#            - ASR_ADDR_PORT=speechrecognition
        entrypoint: /bin/bash -c "source /lucida/tools/python_2_7_9/bin/activate && python app.py"

    imagematching:
        depends_on:
            - base
        build:
            context: .
            dockerfile: docker/imagematching/Dockerfile
        image: lucida/imagematching
        environment:
            - MONGO_PORT_27017_TCP_ADDR=mongodb
        entrypoint: ./opencv_imm/server/imm_server

    questionanswering:
        depends_on:
            - base
            - mongodb
        links:
            - mongodb
        build:
            context: .
            dockerfile: docker/questionanswering/Dockerfile
        image: lucida/questionanswering
        environment:
            - MONGO_PORT_27017_TCP_ADDR=mongodb
        entrypoint: ./start_server.sh

    calendar:
        depends_on:
            - base
        build:
            context: .
            dockerfile: docker/calendar/Dockerfile
        image: lucida/calendar
        entrypoint: ./gradlew run

    speechrecognition:
        depends_on:
            - base
        links:
            - commandcenter
        build:
            context: .
            dockerfile: docker/speechrecognition/Dockerfile
        image: lucida/speechrecognition
        environment:
            - GST_PLUGIN_PATH=/lucida/lucida/speechrecognition/kaldi_gstreamer_asr/kaldi/tools/gst-kaldi-nnet2-online/src
        entrypoint: python kaldigstserver/worker.py -u ws://commancenter:8081/worker/ws/speech -c sample_english_nnet2.yaml

